import type { ThemeConfig } from '../../packages/engine/config/ThemeSchema.ts';

export const guildLedgerTheme: ThemeConfig = {
  id: 'guild-ledger',
  title: 'Guild Ledger',
  version: '0.7.0',
  tagline: 'Sen kahraman değilsin — lonca muhasebecisisin. Partiler ölürken sen kâr yazarsın.',
  startingGold: 15,
  startingParties: [{ id: 'squire', level: 1 }],
  clickBoost: {
    multiplier: 2,
    durationSec: 30,
    cooldownSec: 30,
    tapGoldFactor: 0.1,
  },
  offlineCapHours: 8,
  resources: [
    { id: 'gold', name: 'Altın', icon: 'coin' },
    { id: 'prestige', name: 'İtibar', icon: 'rank' },
  ],
  zones: [
    {
      id: 'rat_cellar',
      name: 'Sıçan Bodrumu',
      icon: 'rat',
      description: 'Yeni maceracılar için ucuz ölüm.',
      unlockGold: 0,
      baseEnemyHp: 9,
      baseGoldPerKill: 2.5,
      deathChance: 0.04,
      questDurationSec: 28,
    },
    {
      id: 'goblin_mine',
      name: 'Goblin Madeni',
      icon: 'pickaxe',
      description: 'Goblinler hem düşman hem fatura kesiyor.',
      unlockGold: 500,
      baseEnemyHp: 22,
      baseGoldPerKill: 7,
      deathChance: 0.1,
      questDurationSec: 40,
    },
    {
      id: 'haunted_crypt',
      name: 'Lanetli Mahzen',
      icon: 'tombstone',
      description: 'Ölüm sigortası burada geçersiz.',
      unlockGold: 4500,
      baseEnemyHp: 70,
      baseGoldPerKill: 24,
      deathChance: 0.18,
      questDurationSec: 55,
    },
    {
      id: 'dragon_vault',
      name: 'Ejderha Kasası',
      icon: 'dragon',
      description: 'Yüksek risk, yüksek kira.',
      unlockGold: 45000,
      baseEnemyHp: 260,
      baseGoldPerKill: 102,
      deathChance: 0.32,
      questDurationSec: 80,
    },
    {
      id: 'infernal_ledger',
      name: 'Cehennem Defteri',
      icon: 'flame',
      description: 'Şeytani faiz oranları. Ölümler vergi indirimi sayılır.',
      unlockGold: 450_000,
      baseEnemyHp: 820,
      baseGoldPerKill: 358,
      deathChance: 0.36,
      questDurationSec: 92,
    },
    {
      id: 'celestial_audit',
      name: 'Göksel Denetim',
      icon: 'halo',
      description: 'Tanrılar bile makbuz ister. Son büyük kâr kapısı.',
      unlockGold: 4_500_000,
      baseEnemyHp: 2800,
      baseGoldPerKill: 1370,
      deathChance: 0.42,
      questDurationSec: 105,
    },
  ],
  partySlots: [
    {
      id: 'squire',
      name: 'Çırak',
      icon: 'sword',
      description: 'Ucuz, değiştirilebilir, vergi kesintisiz.',
      baseCost: 12,
      costGrowth: 1.16,
      baseDps: 1.1,
      unlockZone: 'rat_cellar',
    },
    {
      id: 'cleric',
      name: 'Rahip',
      icon: 'cross',
      description: 'Az ölür, az kazanır. Muhasebe dostu.',
      baseCost: 85,
      costGrowth: 1.18,
      baseDps: 3.5,
      unlockZone: 'rat_cellar',
    },
    {
      id: 'rogue',
      name: 'Hırsız',
      icon: 'key',
      description: 'Ganimet bonusu. Sigorta dolandırıcısı.',
      baseCost: 450,
      costGrowth: 1.21,
      baseDps: 14,
      unlockZone: 'goblin_mine',
    },
    {
      id: 'knight',
      name: 'Şövalye',
      icon: 'shield',
      description: 'Tank. Kirayı geç öder ama öder.',
      baseCost: 2800,
      costGrowth: 1.23,
      baseDps: 48,
      unlockZone: 'haunted_crypt',
    },
    {
      id: 'mage',
      name: 'Büyücü',
      icon: 'orb',
      description: 'AoE faturalandırma uzmanı.',
      baseCost: 14000,
      costGrowth: 1.25,
      baseDps: 170,
      unlockZone: 'dragon_vault',
    },
    {
      id: 'warlock',
      name: 'Warlock',
      icon: 'skull',
      description: 'Karanlık sözleşmeler. Yüksek DPS, yüksek dava riski.',
      baseCost: 85000,
      costGrowth: 1.26,
      baseDps: 420,
      unlockZone: 'infernal_ledger',
    },
    {
      id: 'auditor',
      name: 'Baş Denetçi',
      icon: 'lens',
      description: 'Her vuruşu fatura eder. Geç oyunun son kalemi.',
      baseCost: 420000,
      costGrowth: 1.27,
      baseDps: 1100,
      unlockZone: 'celestial_audit',
    },
  ],
  upgrades: [
    {
      id: 'rent_hike',
      name: 'Kira Artışı',
      description: '+15% altın geliri',
      icon: 'KA',
      baseCost: 45,
      costGrowth: 1.38,
      maxLevel: 20,
      effectPerLevel: 0.15,
      effectType: 'gold_mult',
    },
    {
      id: 'insurance_fraud',
      name: 'Sigorta Dolandırıcılığı',
      description: '-8% parti ölüm şansı',
      icon: 'SD',
      baseCost: 180,
      costGrowth: 1.48,
      maxLevel: 10,
      effectPerLevel: 0.08,
      effectType: 'death_reduce',
    },
    {
      id: 'desk_efficiency',
      name: 'Masa Başı Verimlilik',
      description: '+10% DPS',
      icon: 'MV',
      baseCost: 120,
      costGrowth: 1.42,
      maxLevel: 15,
      effectPerLevel: 0.1,
      effectType: 'dps_mult',
    },
    {
      id: 'night_shift',
      name: 'Gece Vardiyası',
      description: '+20% offline kazanç',
      icon: 'GV',
      baseCost: 450,
      costGrowth: 1.52,
      maxLevel: 8,
      effectPerLevel: 0.2,
      effectType: 'offline_mult',
    },
    {
      id: 'guild_reputation',
      name: 'Lonca İtibarı',
      description: '+5% prestige puanı',
      icon: 'Lİ',
      baseCost: 900,
      costGrowth: 1.58,
      maxLevel: 10,
      effectPerLevel: 0.05,
      effectType: 'prestige_mult',
    },
    {
      id: 'tax_evasion',
      name: 'Vergi Kaçırma',
      description: '+12% altın geliri (geç oyun)',
      icon: 'VK',
      baseCost: 8500,
      costGrowth: 1.56,
      maxLevel: 15,
      effectPerLevel: 0.12,
      effectType: 'gold_mult',
      unlockZone: 'infernal_ledger',
    },
  ],
  prestige: {
    minGoldEarned: 1_000_000,
    currencyName: 'Lonca İtibarı',
    currencyIcon: 'rank',
    multiplierPerPoint: 0.05,
  },
  prestigeShop: [
    {
      id: 'golden_seal',
      name: 'Altın Mühür',
      description: 'Kalıcı +%4 altın geliri',
      icon: 'coin',
      baseCost: 1,
      costGrowth: 1.38,
      maxLevel: 15,
      effectPerLevel: 0.04,
      effectType: 'gold_mult_perm',
    },
    {
      id: 'night_audit',
      name: 'Gece Denetimi',
      description: 'Kalıcı +%6 offline kazanç',
      icon: 'moon',
      baseCost: 2,
      costGrowth: 1.42,
      maxLevel: 10,
      effectPerLevel: 0.06,
      effectType: 'offline_mult_perm',
    },
    {
      id: 'tenant_insurance',
      name: 'Kiracı Sigortası',
      description: 'Kalıcı -%2 ölüm şansı',
      icon: 'shield',
      baseCost: 2,
      costGrowth: 1.45,
      maxLevel: 8,
      effectPerLevel: 0.02,
      effectType: 'death_reduce_perm',
    },
    {
      id: 'opening_balance',
      name: 'Açılış Bakiyesi',
      description: 'Prestige sonrası +30 başlangıç altını',
      icon: 'briefcase',
      baseCost: 1,
      costGrowth: 1.28,
      maxLevel: 12,
      effectPerLevel: 30,
      effectType: 'start_gold_perm',
    },
    {
      id: 'veteran_crew',
      name: 'Kıdemli Ekip',
      description: 'Kalıcı +%5 DPS',
      icon: 'chevron',
      baseCost: 2,
      costGrowth: 1.4,
      maxLevel: 15,
      effectPerLevel: 0.05,
      effectType: 'dps_mult_perm',
    },
    {
      id: 'compound_reputation',
      name: 'Bileşik İtibar',
      description: 'Kalıcı +%5 itibar kazancı',
      icon: 'rank',
      baseCost: 3,
      costGrowth: 1.55,
      maxLevel: 10,
      effectPerLevel: 0.05,
      effectType: 'prestige_mult_perm',
    },
    {
      id: 'expedition_bonus',
      name: 'Sevkiyat İkramiyesi',
      description: 'Kalıcı +%6 görev altını',
      icon: 'banner',
      baseCost: 2,
      costGrowth: 1.42,
      maxLevel: 12,
      effectPerLevel: 0.06,
      effectType: 'quest_gold_perm',
    },
    {
      id: 'legacy_endowment',
      name: 'Miras Vakfı',
      description: 'Kalıcı +%10 altın geliri',
      icon: 'crown',
      baseCost: 8,
      costGrowth: 1.9,
      maxLevel: 5,
      effectPerLevel: 0.1,
      effectType: 'gold_mult_perm',
    },
  ],
  zoneLoot: [
    {
      id: 'trap_wire',
      zoneId: 'rat_cellar',
      craftId: 'rat_trap',
      name: 'Paslı Tel',
      icon: 'wire',
      description: 'Tuzak kurmak için bodrumdan toplanan tel parçaları.',
      dropChancePerKill: 0.0014,
    },
    {
      id: 'iron_shard',
      zoneId: 'goblin_mine',
      craftId: 'goblin_pickaxe',
      name: 'Demir Parçası',
      icon: 'shard',
      description: 'Kazma dövmek için madenden çıkan hurda demir.',
      dropChancePerKill: 0.0009,
    },
    {
      id: 'tomb_wax',
      zoneId: 'haunted_crypt',
      craftId: 'crypt_lantern',
      name: 'Mahzen Mumu',
      icon: 'candle',
      description: 'Feneri beslemek için mahzendeki eski mum kalıntıları.',
      dropChancePerKill: 0.0007,
    },
    {
      id: 'dragon_fang',
      zoneId: 'dragon_vault',
      craftId: 'vault_key',
      name: 'Ejderha Dişi',
      icon: 'fang',
      description: 'Anahtar dövmek için ejderhadan kopan diş.',
      dropChancePerKill: 0.00055,
    },
    {
      id: 'hell_ink',
      zoneId: 'infernal_ledger',
      craftId: 'infernal_stamp',
      name: 'Cehennem Mürekkebi',
      icon: 'quill',
      description: 'Mühür basmak için cehennem defterinden sızan mürekkep.',
      dropChancePerKill: 0.00045,
    },
    {
      id: 'audit_wax',
      zoneId: 'celestial_audit',
      craftId: 'audit_seal',
      name: 'Denetim Balmumu',
      icon: 'wax-drip',
      description: 'Mühür mühürlemek için göksel denetimden alınan balmumu.',
      dropChancePerKill: 0.00035,
    },
  ],
  zoneLootCrafts: [
    {
      id: 'rat_trap',
      lootId: 'trap_wire',
      zoneId: 'rat_cellar',
      name: 'Sıçan Tuzağı',
      icon: 'trap',
      description: 'Paslı tellerden kurulan tuzak. Kalıcı +%5 altın geliri.',
      shardCost: 45,
      effectType: 'gold_mult_perm',
      effectValue: 0.05,
    },
    {
      id: 'goblin_pickaxe',
      lootId: 'iron_shard',
      zoneId: 'goblin_mine',
      name: 'Goblin Kazması',
      icon: 'pickaxe',
      description: 'Demir parçalarından dövülen kazma. Kalıcı +%10 altın geliri.',
      shardCost: 100,
      effectType: 'gold_mult_perm',
      effectValue: 0.1,
    },
    {
      id: 'crypt_lantern',
      lootId: 'tomb_wax',
      zoneId: 'haunted_crypt',
      name: 'Mahzen Feneri',
      icon: 'lantern',
      description: 'Mahzen mumuyla yakılan fener. Kalıcı +%8 DPS.',
      shardCost: 160,
      effectType: 'dps_mult_perm',
      effectValue: 0.08,
    },
    {
      id: 'vault_key',
      lootId: 'dragon_fang',
      zoneId: 'dragon_vault',
      name: 'Kasa Anahtarı',
      icon: 'key',
      description: 'Ejderha dişinden işlenen anahtar. Kalıcı +%12 görev altını.',
      shardCost: 240,
      effectType: 'quest_gold_perm',
      effectValue: 0.12,
    },
    {
      id: 'infernal_stamp',
      lootId: 'hell_ink',
      zoneId: 'infernal_ledger',
      name: 'Cehennem Mühürü',
      icon: 'skull',
      description: 'Cehennem mürekkebiyle basılan mühür. Kalıcı +%10 offline kazanç.',
      shardCost: 320,
      effectType: 'offline_mult_perm',
      effectValue: 0.1,
    },
    {
      id: 'audit_seal',
      lootId: 'audit_wax',
      zoneId: 'celestial_audit',
      name: 'Denetim Mührü',
      icon: 'rank',
      description: 'Denetim balmumuyla mühürlenen mühür. Kalıcı -%4 ölüm şansı.',
      shardCost: 450,
      effectType: 'death_reduce_perm',
      effectValue: 0.04,
    },
  ],
};