import type { ThemeConfig } from '../../packages/engine/config/ThemeSchema.ts';

export const guildLedgerTheme: ThemeConfig = {
  id: 'guild-ledger',
  title: 'Guild Ledger',
  version: '0.2.0',
  tagline: 'Sen kahraman değilsin — lonca muhasebecisisin. Partiler ölürken sen kâr yazarsın.',
  startingGold: 15,
  startingParties: [{ id: 'squire', level: 1 }],
  clickBoost: {
    multiplier: 2,
    durationSec: 30,
    cooldownSec: 30,
    tapGoldFactor: 0.1,
  },
  offlineCapHours: 8,
  resources: [
    { id: 'gold', name: 'Altın', icon: '🪙' },
    { id: 'prestige', name: 'İtibar', icon: '📜' },
  ],
  zones: [
    {
      id: 'rat_cellar',
      name: 'Sıçan Bodrumu',
      icon: '🐀',
      description: 'Yeni maceracılar için ucuz ölüm.',
      unlockGold: 0,
      baseEnemyHp: 9,
      baseGoldPerKill: 2.5,
      deathChance: 0.04,
      questDurationSec: 28,
    },
    {
      id: 'goblin_mine',
      name: 'Goblin Madeni',
      icon: '⛏️',
      description: 'Goblinler hem düşman hem fatura kesiyor.',
      unlockGold: 500,
      baseEnemyHp: 22,
      baseGoldPerKill: 5.5,
      deathChance: 0.1,
      questDurationSec: 40,
    },
    {
      id: 'haunted_crypt',
      name: 'Lanetli Mahzen',
      icon: '💀',
      description: 'Ölüm sigortası burada geçersiz.',
      unlockGold: 4500,
      baseEnemyHp: 70,
      baseGoldPerKill: 16,
      deathChance: 0.18,
      questDurationSec: 55,
    },
    {
      id: 'dragon_vault',
      name: 'Ejderha Kasası',
      icon: '🐉',
      description: 'Yüksek risk, yüksek kira.',
      unlockGold: 45000,
      baseEnemyHp: 260,
      baseGoldPerKill: 70,
      deathChance: 0.32,
      questDurationSec: 80,
    },
  ],
  partySlots: [
    {
      id: 'squire',
      name: 'Çırak',
      icon: '🗡️',
      description: 'Ucuz, değiştirilebilir, vergi kesintisiz.',
      baseCost: 12,
      costGrowth: 1.16,
      baseDps: 1.1,
      unlockZone: 'rat_cellar',
    },
    {
      id: 'cleric',
      name: 'Rahip',
      icon: '✝️',
      description: 'Az ölür, az kazanır. Muhasebe dostu.',
      baseCost: 85,
      costGrowth: 1.18,
      baseDps: 3.5,
      unlockZone: 'rat_cellar',
    },
    {
      id: 'rogue',
      name: 'Hırsız',
      icon: '🗝️',
      description: 'Ganimet bonusu. Sigorta dolandırıcısı.',
      baseCost: 450,
      costGrowth: 1.21,
      baseDps: 14,
      unlockZone: 'goblin_mine',
    },
    {
      id: 'knight',
      name: 'Şövalye',
      icon: '🛡️',
      description: 'Tank. Kirayı geç öder ama öder.',
      baseCost: 2800,
      costGrowth: 1.23,
      baseDps: 48,
      unlockZone: 'haunted_crypt',
    },
    {
      id: 'mage',
      name: 'Büyücü',
      icon: '🔮',
      description: 'AoE faturalandırma uzmanı.',
      baseCost: 14000,
      costGrowth: 1.25,
      baseDps: 170,
      unlockZone: 'dragon_vault',
    },
  ],
  upgrades: [
    {
      id: 'rent_hike',
      name: 'Kira Artışı',
      description: '+15% altın geliri',
      icon: '📈',
      baseCost: 45,
      costGrowth: 1.38,
      maxLevel: 20,
      effectPerLevel: 0.15,
      effectType: 'gold_mult',
    },
    {
      id: 'insurance_fraud',
      name: 'Sigorta Dolandırıcılığı',
      description: '-8% parti ölüm şansı',
      icon: '📋',
      baseCost: 180,
      costGrowth: 1.48,
      maxLevel: 10,
      effectPerLevel: 0.08,
      effectType: 'death_reduce',
    },
    {
      id: 'desk_efficiency',
      name: 'Masa Başı Verimlilik',
      description: '+10% DPS',
      icon: '⚙️',
      baseCost: 120,
      costGrowth: 1.42,
      maxLevel: 15,
      effectPerLevel: 0.1,
      effectType: 'dps_mult',
    },
    {
      id: 'night_shift',
      name: 'Gece Vardiyası',
      description: '+20% offline kazanç',
      icon: '🌙',
      baseCost: 450,
      costGrowth: 1.52,
      maxLevel: 8,
      effectPerLevel: 0.2,
      effectType: 'offline_mult',
    },
    {
      id: 'guild_reputation',
      name: 'Lonca İtibarı',
      description: '+5% prestige puanı',
      icon: '🏛️',
      baseCost: 900,
      costGrowth: 1.58,
      maxLevel: 10,
      effectPerLevel: 0.05,
      effectType: 'prestige_mult',
    },
  ],
  prestige: {
    minGoldEarned: 1_000_000,
    currencyName: 'Lonca İtibarı',
    currencyIcon: '📜',
    multiplierPerPoint: 0.05,
  },
};