import type { ThemeConfig } from '../../packages/engine/config/ThemeSchema.ts';

export const guildLedgerTheme: ThemeConfig = {
  id: 'guild-ledger',
  title: 'Guild Ledger',
  version: '0.5.1',
  tagline: 'Sen kahraman değilsin — lonca muhasebecisisin. Partiler ölürken sen kâr yazarsın.',
  startingGold: 15,
  startingParties: [{ id: 'squire', level: 1 }],
  clickBoost: {
    multiplier: 2,
    durationSec: 30,
    cooldownSec: 30,
    tapGoldFactor: 0.1,
  },
  offlineCapHours: 8,
  resources: [
    { id: 'gold', name: 'Altın', icon: '🪙' },
    { id: 'prestige', name: 'İtibar', icon: '📜' },
  ],
  zones: [
    {
      id: 'rat_cellar',
      name: 'Sıçan Bodrumu',
      icon: '🐀',
      description: 'Yeni maceracılar için ucuz ölüm.',
      unlockGold: 0,
      baseEnemyHp: 9,
      baseGoldPerKill: 2.5,
      deathChance: 0.04,
      questDurationSec: 28,
    },
    {
      id: 'goblin_mine',
      name: 'Goblin Madeni',
      icon: '⛏️',
      description: 'Goblinler hem düşman hem fatura kesiyor.',
      unlockGold: 500,
      baseEnemyHp: 22,
      baseGoldPerKill: 7,
      deathChance: 0.1,
      questDurationSec: 40,
    },
    {
      id: 'haunted_crypt',
      name: 'Lanetli Mahzen',
      icon: '💀',
      description: 'Ölüm sigortası burada geçersiz.',
      unlockGold: 4500,
      baseEnemyHp: 70,
      baseGoldPerKill: 24,
      deathChance: 0.18,
      questDurationSec: 55,
    },
    {
      id: 'dragon_vault',
      name: 'Ejderha Kasası',
      icon: '🐉',
      description: 'Yüksek risk, yüksek kira.',
      unlockGold: 45000,
      baseEnemyHp: 260,
      baseGoldPerKill: 102,
      deathChance: 0.32,
      questDurationSec: 80,
    },
    {
      id: 'infernal_ledger',
      name: 'Cehennem Defteri',
      icon: '🔥',
      description: 'Şeytani faiz oranları. Ölümler vergi indirimi sayılır.',
      unlockGold: 450_000,
      baseEnemyHp: 820,
      baseGoldPerKill: 358,
      deathChance: 0.36,
      questDurationSec: 92,
    },
    {
      id: 'celestial_audit',
      name: 'Göksel Denetim',
      icon: '✨',
      description: 'Tanrılar bile makbuz ister. Son büyük kâr kapısı.',
      unlockGold: 4_500_000,
      baseEnemyHp: 2800,
      baseGoldPerKill: 1370,
      deathChance: 0.42,
      questDurationSec: 105,
    },
  ],
  partySlots: [
    {
      id: 'squire',
      name: 'Çırak',
      icon: '🗡️',
      description: 'Ucuz, değiştirilebilir, vergi kesintisiz.',
      baseCost: 12,
      costGrowth: 1.16,
      baseDps: 1.1,
      unlockZone: 'rat_cellar',
    },
    {
      id: 'cleric',
      name: 'Rahip',
      icon: '✝️',
      description: 'Az ölür, az kazanır. Muhasebe dostu.',
      baseCost: 85,
      costGrowth: 1.18,
      baseDps: 3.5,
      unlockZone: 'rat_cellar',
    },
    {
      id: 'rogue',
      name: 'Hırsız',
      icon: '🗝️',
      description: 'Ganimet bonusu. Sigorta dolandırıcısı.',
      baseCost: 450,
      costGrowth: 1.21,
      baseDps: 14,
      unlockZone: 'goblin_mine',
    },
    {
      id: 'knight',
      name: 'Şövalye',
      icon: '🛡️',
      description: 'Tank. Kirayı geç öder ama öder.',
      baseCost: 2800,
      costGrowth: 1.23,
      baseDps: 48,
      unlockZone: 'haunted_crypt',
    },
    {
      id: 'mage',
      name: 'Büyücü',
      icon: '🔮',
      description: 'AoE faturalandırma uzmanı.',
      baseCost: 14000,
      costGrowth: 1.25,
      baseDps: 170,
      unlockZone: 'dragon_vault',
    },
    {
      id: 'warlock',
      name: 'Warlock',
      icon: '☠️',
      description: 'Karanlık sözleşmeler. Yüksek DPS, yüksek dava riski.',
      baseCost: 85000,
      costGrowth: 1.26,
      baseDps: 420,
      unlockZone: 'infernal_ledger',
    },
    {
      id: 'auditor',
      name: 'Baş Denetçi',
      icon: '🕵️',
      description: 'Her vuruşu fatura eder. Geç oyunun son kalemi.',
      baseCost: 420000,
      costGrowth: 1.27,
      baseDps: 1100,
      unlockZone: 'celestial_audit',
    },
  ],
  upgrades: [
    {
      id: 'rent_hike',
      name: 'Kira Artışı',
      description: '+15% altın geliri',
      icon: '📈',
      baseCost: 45,
      costGrowth: 1.38,
      maxLevel: 20,
      effectPerLevel: 0.15,
      effectType: 'gold_mult',
    },
    {
      id: 'insurance_fraud',
      name: 'Sigorta Dolandırıcılığı',
      description: '-8% parti ölüm şansı',
      icon: '📋',
      baseCost: 180,
      costGrowth: 1.48,
      maxLevel: 10,
      effectPerLevel: 0.08,
      effectType: 'death_reduce',
    },
    {
      id: 'desk_efficiency',
      name: 'Masa Başı Verimlilik',
      description: '+10% DPS',
      icon: '⚙️',
      baseCost: 120,
      costGrowth: 1.42,
      maxLevel: 15,
      effectPerLevel: 0.1,
      effectType: 'dps_mult',
    },
    {
      id: 'night_shift',
      name: 'Gece Vardiyası',
      description: '+20% offline kazanç',
      icon: '🌙',
      baseCost: 450,
      costGrowth: 1.52,
      maxLevel: 8,
      effectPerLevel: 0.2,
      effectType: 'offline_mult',
    },
    {
      id: 'guild_reputation',
      name: 'Lonca İtibarı',
      description: '+5% prestige puanı',
      icon: '🏛️',
      baseCost: 900,
      costGrowth: 1.58,
      maxLevel: 10,
      effectPerLevel: 0.05,
      effectType: 'prestige_mult',
    },
    {
      id: 'tax_evasion',
      name: 'Vergi Kaçırma',
      description: '+12% altın geliri (geç oyun)',
      icon: '💸',
      baseCost: 8500,
      costGrowth: 1.56,
      maxLevel: 15,
      effectPerLevel: 0.12,
      effectType: 'gold_mult',
      unlockZone: 'infernal_ledger',
    },
  ],
  prestige: {
    minGoldEarned: 1_000_000,
    currencyName: 'Lonca İtibarı',
    currencyIcon: '📜',
    multiplierPerPoint: 0.05,
  },
  prestigeShop: [
    {
      id: 'golden_seal',
      name: 'Altın Mühür',
      description: 'Kalıcı +%4 altın geliri',
      icon: '🔏',
      baseCost: 1,
      costGrowth: 1.38,
      maxLevel: 15,
      effectPerLevel: 0.04,
      effectType: 'gold_mult_perm',
    },
    {
      id: 'night_audit',
      name: 'Gece Denetimi',
      description: 'Kalıcı +%6 offline kazanç',
      icon: '🌙',
      baseCost: 2,
      costGrowth: 1.42,
      maxLevel: 10,
      effectPerLevel: 0.06,
      effectType: 'offline_mult_perm',
    },
    {
      id: 'tenant_insurance',
      name: 'Kiracı Sigortası',
      description: 'Kalıcı -%2 ölüm şansı',
      icon: '🛡️',
      baseCost: 2,
      costGrowth: 1.45,
      maxLevel: 8,
      effectPerLevel: 0.02,
      effectType: 'death_reduce_perm',
    },
    {
      id: 'opening_balance',
      name: 'Açılış Bakiyesi',
      description: 'Prestige sonrası +30 başlangıç altını',
      icon: '💼',
      baseCost: 1,
      costGrowth: 1.28,
      maxLevel: 12,
      effectPerLevel: 30,
      effectType: 'start_gold_perm',
    },
  ],
  zoneLoot: [
    {
      id: 'rat_whisker',
      zoneId: 'rat_cellar',
      craftId: 'rat_trap',
      name: 'Sıçan Bıyığı',
      icon: '🪶',
      description: 'Bodrumdan düşen tuhaf ganimet.',
      dropChancePerKill: 0.002,
    },
    {
      id: 'iron_shard',
      zoneId: 'goblin_mine',
      craftId: 'goblin_pickaxe',
      name: 'Demir Parçası',
      icon: '🔩',
      description: 'Goblin madeninden çıkan nadir hurda.',
      dropChancePerKill: 0.0012,
    },
    {
      id: 'bone_chip',
      zoneId: 'haunted_crypt',
      craftId: 'crypt_lantern',
      name: 'Kemik Parçası',
      icon: '🦴',
      description: 'Mahzen kemiklerinden süzülen parça.',
      dropChancePerKill: 0.0009,
    },
    {
      id: 'dragon_scale',
      zoneId: 'dragon_vault',
      craftId: 'vault_key',
      name: 'Ejderha Pulu',
      icon: '🐲',
      description: 'Kasadaki ejderhadan kopan pul.',
      dropChancePerKill: 0.0007,
    },
    {
      id: 'hell_ember',
      zoneId: 'infernal_ledger',
      craftId: 'infernal_stamp',
      name: 'Cehennem Koru',
      icon: '🔥',
      description: 'Cehennem defterinden sızan kor.',
      dropChancePerKill: 0.0006,
    },
    {
      id: 'star_dust',
      zoneId: 'celestial_audit',
      craftId: 'audit_seal',
      name: 'Yıldız Tozu',
      icon: '✨',
      description: 'Göksel denetimden dökülen toz.',
      dropChancePerKill: 0.0005,
    },
  ],
  zoneLootCrafts: [
    {
      id: 'rat_trap',
      lootId: 'rat_whisker',
      zoneId: 'rat_cellar',
      name: 'Sıçan Tuzağı',
      icon: '🪤',
      description: 'Kalıcı +%4 altın geliri. Prestige sonrası kalır.',
      shardCost: 12,
      effectType: 'gold_mult_perm',
      effectValue: 0.04,
    },
    {
      id: 'goblin_pickaxe',
      lootId: 'iron_shard',
      zoneId: 'goblin_mine',
      name: 'Goblin Kazması',
      icon: '⛏️',
      description: 'Kalıcı +%8 altın geliri. Prestige sonrası kalır. Düşüş oranını artırmaz.',
      shardCost: 20,
      effectType: 'gold_mult_perm',
      effectValue: 0.08,
    },
    {
      id: 'crypt_lantern',
      lootId: 'bone_chip',
      zoneId: 'haunted_crypt',
      name: 'Mahzen Feneri',
      icon: '🕯️',
      description: 'Kalıcı +%6 DPS. Prestige sonrası kalır.',
      shardCost: 18,
      effectType: 'dps_mult_perm',
      effectValue: 0.06,
    },
    {
      id: 'vault_key',
      lootId: 'dragon_scale',
      zoneId: 'dragon_vault',
      name: 'Kasa Anahtarı',
      icon: '🗝️',
      description: 'Kalıcı +%10 görev altını. Prestige sonrası kalır.',
      shardCost: 22,
      effectType: 'quest_gold_perm',
      effectValue: 0.1,
    },
    {
      id: 'infernal_stamp',
      lootId: 'hell_ember',
      zoneId: 'infernal_ledger',
      name: 'Cehennem Mühürü',
      icon: '👹',
      description: 'Kalıcı +%8 offline kazanç. Prestige sonrası kalır.',
      shardCost: 24,
      effectType: 'offline_mult_perm',
      effectValue: 0.08,
    },
    {
      id: 'audit_seal',
      lootId: 'star_dust',
      zoneId: 'celestial_audit',
      name: 'Denetim Mührü',
      icon: '📋',
      description: 'Kalıcı -%3 ölüm şansı. Prestige sonrası kalır.',
      shardCost: 28,
      effectType: 'death_reduce_perm',
      effectValue: 0.03,
    },
  ],
};